spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    contexts: test
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 7777
  error:
    include-message: always