describe("Lending history of a borrower test", () => {
  it("Visits page", () => {
    cy.visit("http://localhost:4200/")
  })
  it("Adds a borrower", () => {
    cy.get("a[routerLink='/borrowers'").click()
    cy.get(".btn-primary").click()
    cy.get(".form-control").eq(1).should("have.class", "is-invalid")
    cy.get(".form-control").eq(2).should("have.class", "is-invalid")
    cy.get(".modal-footer>button").should("be.disabled")
    cy.get(".form-control").eq(1).type("cyFirst", { force: true })
    cy.get(".form-control").eq(2).type("cyLast", { force: true })
    cy.get(".form-control").eq(1).should("have.class", "is-valid")
    cy.get(".form-control").eq(2).should("have.class", "is-valid")
    cy.get(".modal-footer>button").click()
    cy.contains("Borrower successfully added")
    cy.get("input[name='searchTerm']").type("cyFirst")
    cy.contains("Found 1")
    cy.get("table").contains("cyFirst")
    cy.get("table").contains("cyLast")
  })
  it("Adds a book", () => {
    cy.get("a[routerLink='/books/available'").click()
    cy.get(".btn-primary").click()
    cy.get(".form-control").eq(1).should("have.class", "is-invalid")
    cy.get(".form-control").eq(2).should("have.class", "is-invalid")
    cy.get(".modal-footer>button").should("be.disabled")
    cy.get(".form-control").eq(1).type("cyAuthor", { force: true })
    cy.get(".form-control").eq(2).type("cyTitle", { force: true })
    cy.get(".form-control").eq(1).should("have.class", "is-valid")
    cy.get(".form-control").eq(2).should("have.class", "is-valid")
    cy.get(".modal-footer>button").click()
    cy.contains("Book successfully added")
  })
  it("Lends a book", () => {
    cy.get("input[name='searchTerm']").type("cyAuthor")
    cy.get("i[ngbTooltip='Lend']").click()
    cy.get(".form-control").eq(1).should("have.class", "is-invalid")
    cy.get(".modal-footer>button").should("be.disabled")
    cy.get(".form-control").eq(1).type("cyFirst ", { force: true })
    cy.get(".form-control").eq(1).type("cyLast", { force: true })
    cy.get("button").contains("cyFirst").click()
    cy.get(".form-control").eq(1).should("have.class", "is-valid")
    cy.get(".modal-footer>button").click()
    cy.contains("Book successfully lent")
  })
  it("Check lending history of a borrower", () => {
    cy.get("a[routerLink='/lendings'").click()
    cy.get("input").click()
    cy.get("input").type("cyFirst ", { force: true })
    cy.get("input").type("cyLast", { force: true })
    cy.get(".dropdown-item").click()
    cy.get(".btn-primary").click()
    cy.contains("Currently lent books")
    cy.contains("Current lendings")
    cy.get("table").eq(0).contains("cyAuthor")
    cy.get("table").eq(0).contains("cyTitle")
    cy.get("table").eq(1).contains("cyFirst")
    cy.get("table").eq(1).contains("cyLast")
    cy.get("table").eq(1).contains("No comment")
  })
  it("Return book from lending history view", () => {
    cy.get("i[ngbTooltip='Return']").click()
    cy.get(".btn-outline-primary").click()
    cy.contains("Past lendings")
    cy.contains("Book successfully returned")
    cy.get("table").eq(0).contains("cyFirst")
    cy.get("table").eq(0).contains("cyLast")
    cy.get("table").eq(0).contains("No comment")
  })
  it("Lends a book again", () => {
    cy.get("a[routerLink='/books/available'").click()
    cy.get("input[name='searchTerm']").clear()
    cy.get("input[name='searchTerm']").type("cyAuthor")
    cy.get("i[ngbTooltip='Lend']").click()
    cy.get(".form-control").eq(1).should("have.class", "is-invalid")
    cy.get(".modal-footer>button").should("be.disabled")
    cy.get(".form-control").eq(1).type("cyFirst cyLas", { force: true })
    cy.get(".form-control").eq(1).type("t", { force: true })
    cy.get("button").contains("cyFirst").click()
    cy.get(".form-control").eq(1).should("have.class", "is-valid")
    cy.get(".modal-footer>button").click()
    cy.contains("Book successfully lent")
  })
  it("Check lending history of a borrower again", () => {
    cy.get("a[routerLink='/lendings'").click()
    cy.get("input").click()
    cy.get("input").type("cyFirst ", { force: true })
    cy.get("input").type("cyLast", { force: true })
    cy.get(".dropdown-item").click()
    cy.get(".btn-primary").click()
    cy.contains("Currently lent books")
    cy.contains("Current lendings")
    cy.get("table").eq(0).contains("cyAuthor")
    cy.get("table").eq(0).contains("cyTitle")
    cy.get("table").eq(1).contains("cyFirst")
    cy.get("table").eq(1).contains("cyLast")
    cy.get("table").eq(1).contains("No comment")
  })
  it("Return book from lending history view again", () => {
    cy.get("i[ngbTooltip='Return']").click()
    cy.get(".btn-outline-primary").click()
    cy.contains("Book successfully returned")
    cy.contains("Past lendings")
    cy.get("table").eq(0).contains("cyFirst")
    cy.get("table").eq(0).contains("cyLast")
    cy.get("table").eq(0).contains("No comment")
  })
  it("Removes past lending", () => {
    cy.get(".ti-trash").eq(0).click()
    cy.get(".btn-outline-danger").click()
    cy.contains("Lending deleted")
  })
  it("Deletes a book", () => {
    cy.get("a[routerLink='/books/available'").click()
    cy.get(".ti-trash").click()
    cy.get(".btn-outline-danger").click()
    cy.contains("Book deleted")
    cy.contains("Found 0")
  })
  it("Deletes a borrower", () => {
    cy.get("a[routerLink='/borrowers'").click()
    cy.contains("Found 1")
    cy.get("table").contains("cyFirst")
    cy.get("table").contains("cyLast")
    cy.get(".ti-trash").click()
    cy.get(".btn-outline-danger").click()
    cy.contains("Borrower deleted")
    cy.contains("Found 0")
  })
})
