describe("Managing categories test", () => {
  it("Visits page", () => {
    cy.visit("http://localhost:4200/")
  })
  it("Adds a category", () => {
    cy.get("a[routerLink='/categories']").click()
    cy.get(".btn-primary").click()
    cy.get(".form-control").eq(1).should("have.class", "is-invalid")
    cy.get(".modal-footer>button").should("be.disabled")
    cy.get(".form-control").eq(1).type("Cycategory", { force: true })
    cy.get(".form-control").eq(1).should("have.class", "is-valid")
    cy.get(".modal-footer>button").click()
    cy.contains("Category successfully added")
    cy.get("input[name='searchTerm']").type("cycategory")
    cy.contains("Found 1")
  })
  it("Adds a book", () => {
    cy.get("a[routerLink='/books/available'").click()
    cy.get(".btn-primary").click()
    cy.get(".form-control").eq(1).should("have.class", "is-invalid")
    cy.get(".form-control").eq(2).should("have.class", "is-invalid")
    cy.get(".modal-footer>button").should("be.disabled")
    cy.get(".form-control").eq(1).type("cyAuthor", { force: true })
    cy.get(".form-control").eq(2).type("cyTitle", { force: true })
    cy.get("#dropdownCategory").click().then((v) => {
      cy.get("button").contains("Cycategory").click()
      cy.get(".form-control").eq(1).should("have.class", "is-valid")
      cy.get(".form-control").eq(2).should("have.class", "is-valid")
      cy.get(".modal-footer>button").click()
      cy.contains("Book successfully added")
      cy.get("input[name='searchTerm']").type("cyAuthor")
      cy.contains("Cycategory")
    })
  })
  it("Deletes a category", () => {
    cy.get("a[routerLink='/categories'").click()
    cy.contains("Found 1")
    cy.get("td").contains("1")
    cy.get(".ti-trash").click()
    cy.get(".btn-outline-danger").click()
    cy.contains("Category deleted")
    cy.contains("Found 0")
  })
  it("Deletes a book", () => {
    cy.get("a[routerLink='/books/available'").click()
    cy.contains("Default")
    cy.get(".ti-trash").click()
    cy.get(".btn-outline-danger").click()
    cy.contains("Book deleted")
    cy.contains("Found 0")
  })
});
