describe("Data presentation test", () => {
  it("Visits page", () => {
    cy.intercept("GET", "/api/books/available", {
      fixture: "available-books.json",
    })
    cy.visit("http://localhost:4200/books/available")
  })
  it("Sorts available books", () => {
    cy.intercept("GET", "/api/books/available", {
      fixture: "available-books.json",
    })
    cy.get("a[routerLink='/books/available'").click()
    cy.get("th").contains("Id").click()
    cy.get("th").contains("Id").should("have.class", "asc")
    cy.get("td").eq(0).contains("1")
    cy.get("th").contains("Id").click()
    cy.get("th").contains("Id").should("have.class", "desc")
    cy.get("td").eq(0).contains("99")
    cy.get("th").contains("Author").click()
    cy.get("th").contains("Id").should("not.have.class", "asc")
    cy.get("th").contains("Id").should("not.have.class", "desc")
    cy.get("th").contains("Author").should("have.class", "asc")
    cy.get("td").eq(1).contains("aaa")
    cy.get("th").contains("Author").click()
    cy.get("th").contains("Author").should("have.class", "desc")
    cy.get("td").eq(1).contains("zzz")

    cy.get("th").contains("Title").click()
    cy.get("th").contains("Author").should("not.have.class", "asc")
    cy.get("th").contains("Author").should("not.have.class", "desc")
    cy.get("th").contains("Title").should("have.class", "asc")
    cy.get("td").eq(2).contains("aaaa")
    cy.get("th").contains("Title").click()
    cy.get("th").contains("Title").should("have.class", "desc")
    cy.get("td").eq(2).contains("zzzz")

    cy.get("th").contains("Category").click()
    cy.get("th").contains("Title").should("not.have.class", "asc")
    cy.get("th").contains("Title").should("not.have.class", "desc")
    cy.get("th").contains("Category").should("have.class", "asc")
    cy.get("td").eq(3).contains("Default")
    cy.get("th").contains("Category").click()
    cy.get("th").contains("Category").should("have.class", "desc")
    cy.get("td").eq(3).contains("Programming")
  })
  it("Changes page in available books", () => {
    cy.get("th").contains("Id").click()
    cy.get("a").contains("»").click()
    cy.get("td").eq(0).contains("48")
    cy.get("th").contains("Id").click()
    cy.get("td").eq(0).contains("51")
  })
  it("Changes items per page in available books", () => {
    cy.get(".custom-select").select("2: 20")
    cy.contains("first")
    cy.contains("last")
  })
  it("Sorts categories", () => {
    cy.intercept("GET", "/api/categories/count", {
      fixture: "categories.json",
    })
    cy.get("a[routerLink='/categories'").click()
    cy.get("th").contains("Id").click()
    cy.get("th").contains("Id").should("have.class", "asc")
    cy.get("td").eq(0).contains("1")
    cy.get("th").contains("Id").click()
    cy.get("th").contains("Id").should("have.class", "desc")
    cy.get("td").eq(0).contains("99")
    cy.get("th").contains("Name").click()
    cy.get("th").contains("Id").should("not.have.class", "asc")
    cy.get("th").contains("Id").should("not.have.class", "desc")
    cy.get("th").contains("Name").should("have.class", "asc")
    cy.get("td").eq(1).contains("Aaa")
    cy.get("th").contains("Name").click()
    cy.get("th").contains("Name").should("have.class", "desc")
    cy.get("td").eq(1).contains("Testing")

    cy.get("th").contains("Number").click()
    cy.get("th").contains("Name").should("not.have.class", "asc")
    cy.get("th").contains("Name").should("not.have.class", "desc")
    cy.get("th").contains("Number").should("have.class", "asc")
    cy.get("td").eq(2).contains("0")
    cy.get("th").contains("Number").click()
    cy.get("th").contains("Number").should("have.class", "desc")
    cy.get("td").eq(2).contains("10")
  })
  it("Changes page in categories", () => {
    cy.get("th").contains("Id").click()
    cy.get("a").contains("»").click()
    cy.get("td").eq(0).contains("6")
    cy.get("th").contains("Id").click()
    cy.get("td").eq(0).contains("5")
  })
  it("Changes items per page in categories", () => {
    cy.get(".custom-select").select("2: 20")
    cy.contains("Last")
    cy.contains("Default")
  })
  it("Sorts borrowers", () => {
    cy.intercept("GET", "/api/borrowers", { fixture: "borrowers.json" })
    cy.get("a[routerLink='/borrowers'").click()
    cy.get("th").contains("Id").click()
    cy.get("th").contains("Id").should("have.class", "asc")
    cy.get("td").eq(0).contains("1")
    cy.get("th").contains("Id").click()
    cy.get("th").contains("Id").should("have.class", "desc")
    cy.get("td").eq(0).contains("66")
    cy.get("th").contains("First").click()
    cy.get("th").contains("Id").should("not.have.class", "asc")
    cy.get("th").contains("Id").should("not.have.class", "desc")
    cy.get("th").contains("First").should("have.class", "asc")
    cy.get("td").eq(1).contains("aaaaa")
    cy.get("th").contains("First").click()
    cy.get("th").contains("First").should("have.class", "desc")
    cy.get("td").eq(1).contains("zzzz")

    cy.get("th").contains("Last").click()
    cy.get("th").contains("First").should("not.have.class", "asc")
    cy.get("th").contains("First").should("not.have.class", "desc")
    cy.get("th").contains("Last").should("have.class", "asc")
    cy.get("td").eq(2).contains("cyLast")
    cy.get("th").contains("Last").click()
    cy.get("th").contains("Last").should("have.class", "desc")
    cy.get("td").eq(2).contains("zzzzz")
  })
  it("Changes page in categories", () => {
    cy.get("th").contains("Id").click()
    cy.get("a").contains("»").click()
    cy.get("td").eq(0).contains("7")
    cy.get("th").contains("Id").click()
    cy.get("td").eq(0).contains("2")
  })
  it("Changes items per page in categories", () => {
    cy.get(".custom-select").select("2: 20")
    cy.contains("66")
    cy.contains("1")
  })
  it("Sorts currently lent books in lending history", () => {
    cy.intercept("GET", "/api/borrowers", { fixture: "borrowers.json" })
    cy.intercept(
      "GET",
      "/api/lendings/history?firstName=cyFirst&lastName=cyLast",
      { fixture: "lending-history.json" }
    )
    cy.get("a[routerLink='/lendings'").click()
    cy.get("input").type("cyFirst ", { force: true })
    cy.get("input").type("cyLast", { force: true })
    cy.get(".dropdown-item").click()
    cy.get(".btn-primary").click()

    cy.get("table").eq(0).within(($table) => {
      cy.get("th").contains("Id").click()
      cy.get("th").contains("Id").should("have.class", "asc")
      cy.get("td").eq(0).contains("11")
      cy.contains("Id").click()
      cy.get("th").contains("Id").should("have.class", "desc")
      cy.get("td").eq(0).contains("16")

      cy.get("th").contains("Author").click()
      cy.get("th").contains("Id").should("not.have.class", "asc")
      cy.get("th").contains("Id").should("not.have.class", "desc")
      cy.get("th").contains("Author").should("have.class", "asc")
      cy.get("td").eq(1).contains("12Autor")
      cy.get("th").contains("Author").click()
      cy.get("th").contains("Author").should("have.class", "desc")
      cy.get("td").eq(1).contains("Yyyy")

      cy.get("th").contains("Title").click()
      cy.get("th").contains("Author").should("not.have.class", "asc")
      cy.get("th").contains("Author").should("not.have.class", "desc")
      cy.get("th").contains("Title").should("have.class", "asc")
      cy.get("td").eq(2).contains("12Tytul")
      cy.get("th").contains("Title").click()
      cy.get("th").contains("Title").should("have.class", "desc")
      cy.get("td").eq(2).contains("Uuuuu")

      cy.get("th").contains("Category").click()
      cy.get("th").contains("Title").should("not.have.class", "asc")
      cy.get("th").contains("Title").should("not.have.class", "desc")
      cy.get("th").contains("Category").should("have.class", "asc")
      cy.get("td").eq(3).contains("Default")
      cy.get("th").contains("Category").click()
      cy.get("th").contains("Category").should("have.class", "desc")
      cy.get("td").eq(3).contains("Testing")
    })
  })
  it("Changes page in currently lent books in lending history", () => {
    cy.get("table").eq(0).within(($table) => {
      cy.get("th").contains("Id").click()
    })
    cy.get("a").contains("»").eq(0).click()
    cy.get("table").eq(0).within(($table) => {
      cy.get("td").eq(0).contains("16")
      cy.get("th").contains("Id").click()
      cy.get("td").eq(0).contains("11")
    })
  })
  it("Changes items per page in currently lent books", () => {
    cy.get(".custom-select").eq(0).select("2: 20")
    cy.get("table").eq(0).contains("11")
    cy.get("table").eq(0).contains("16")
  })
  it("Sorts current lendings in lending history", () => {
    cy.get("table").eq(1).within(($table) => {
      cy.get("th").contains("Book").click()
      cy.get("th").contains("Book").should("have.class", "asc")
      cy.get("td").eq(0).contains("11")
      cy.contains("Book").click()
      cy.get("th").contains("Book").should("have.class", "desc")
      cy.get("td").eq(0).contains("16")

      cy.get("th").contains("Date").click()
      cy.get("th").contains("Book").should("not.have.class", "asc")
      cy.get("th").contains("Book").should("not.have.class", "desc")
      cy.get("th").contains("Date").should("have.class", "asc")
      cy.get("td").eq(1).contains("2021-02-11")
      cy.get("th").contains("Date").click()
      cy.get("th").contains("Date").should("have.class", "desc")
      cy.get("td").eq(1).contains("2021-03-15")

      cy.get("th").contains("First").click()
      cy.get("th").contains("Date").should("not.have.class", "asc")
      cy.get("th").contains("Date").should("not.have.class", "desc")
      cy.get("th").contains("First").should("have.class", "asc")
      cy.get("td").eq(2).contains("cyFirst")
      cy.get("th").contains("First").click()
      cy.get("th").contains("First").should("have.class", "desc")
      cy.get("td").eq(2).contains("cyFirst")

      cy.get("th").contains("Last").click()
      cy.get("th").contains("First").should("not.have.class", "asc")
      cy.get("th").contains("First").should("not.have.class", "desc")
      cy.get("th").contains("Last").should("have.class", "asc")
      cy.get("td").eq(3).contains("cyLast")
      cy.get("th").contains("Last").click()
      cy.get("th").contains("Last").should("have.class", "desc")
      cy.get("td").eq(3).contains("cyLast")
    })
  })
  it("Changes page in current lendings in lending history", () => {
    cy.get("table").eq(1).within(($table) => {
      cy.get("th").contains("Book").click()
    })
    cy.get("a[aria-label='Next'").eq(1).click()
    cy.get("table").eq(1).within(($table) => {
      cy.get("td").eq(0).contains("16")
      cy.get("th").contains("Book").click()
      cy.get("td").eq(0).contains("11")
    })
  })
  it("Changes items per page in current lendings", () => {
    cy.get(".custom-select").eq(1).select("2: 20")
    cy.get("table").eq(1).contains("11")
    cy.get("table").eq(1).contains("16")
  })
  it("Sorts past lendings in lending history", () => {
    cy.get("table").eq(2).within(($table) => {
      cy.get("th").contains("Book").click()
      cy.get("th").contains("Book").should("have.class", "asc")
      cy.get("td").eq(0).contains("1")
      cy.contains("Book").click()
      cy.get("th").contains("Book").should("have.class", "desc")
      cy.get("td").eq(0).contains("3")

      cy.get("th").contains("Date lent").click()
      cy.get("th").contains("Book").should("not.have.class", "asc")
      cy.get("th").contains("Book").should("not.have.class", "desc")
      cy.get("th").contains("Date lent").should("have.class", "asc")
      cy.get("td").eq(1).contains("2019-04-20")
      cy.get("th").contains("Date lent").click()
      cy.get("th").contains("Date lent").should("have.class", "desc")
      cy.get("td").eq(1).contains("2020-06-20")

      cy.get("th").contains("Date returned").click()
      cy.get("th").contains("Date lent").should("not.have.class", "asc")
      cy.get("th").contains("Date lent").should("not.have.class", "desc")
      cy.get("th").contains("Date returned").should("have.class", "asc")
      cy.get("td").eq(2).contains("2019-05-20")
      cy.get("th").contains("Date returned").click()
      cy.get("th").contains("Date returned").should("have.class", "desc")
      cy.get("td").eq(2).contains("2020-07-20")

      cy.get("th").contains("First").click()
      cy.get("th").contains("Date returned").should("not.have.class", "asc")
      cy.get("th").contains("Date returned").should("not.have.class", "desc")
      cy.get("th").contains("First").should("have.class", "asc")
      cy.get("td").eq(3).contains("cyFirst")
      cy.get("th").contains("First").click()
      cy.get("th").contains("First").should("have.class", "desc")
      cy.get("td").eq(3).contains("cyFirst")

      cy.get("th").contains("Last").click()
      cy.get("th").contains("First").should("not.have.class", "asc")
      cy.get("th").contains("First").should("not.have.class", "desc")
      cy.get("th").contains("Last").should("have.class", "asc")
      cy.get("td").eq(4).contains("cyLast")
      cy.get("th").contains("Last").click()
      cy.get("th").contains("Last").should("have.class", "desc")
      cy.get("td").eq(4).contains("cyLast")
    })
  })
  it("Changes page in past lendings in lending history", () => {
    cy.get("table").eq(2).within(($table) => {
      cy.get("th").contains("Book").click()
    })
    cy.get("a[aria-label='Next'").eq(2).click()
    cy.get("table").eq(2).within(($table) => {
      cy.get("td").eq(0).contains("3")
      cy.get("th").contains("Book").click()
      cy.get("td").eq(0).contains("1")
    })
  })
  it("Changes items per page in past lendings", () => {
    cy.get(".custom-select").eq(2).select("2: 20")
    cy.get("table").eq(1).contains("3")
    cy.get("table").eq(1).contains("1")
  })
})
